# Generated by Django 4.1.5 on 2023-01-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('switch', models.CharField(max_length=200)),
                ('rxlevel', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceCounters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_name', models.CharField(max_length=200)),
                ('report_date', models.DateTimeField(verbose_name='report_date')),
                ('switch', models.CharField(max_length=200)),
                ('int_desc', models.CharField(max_length=300)),
            ],
        ),
    ]
