# Generated by Django 4.1.6 on 2023-02-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jns', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Final',
            new_name='Fiber',
        ),
    ]
