# Generated by Django 4.1.6 on 2023-02-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jns', '0002_rename_final_fiber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacecounters',
            name='report_date',
            field=models.DateField(verbose_name='report_date'),
        ),
    ]
