# Generated by Django 4.2 on 2023-04-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jns', '0004_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiber',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
